server:
  port: 80

#database

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5433/platzi-market
    username: postgres
    password: ercilla,13